import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainContext from "@/contexts/MainContext";
import { ToastContainer } from "react-toastify";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" overflow-x-hidden " >
      <body className=" bg-black ">
        

          {children}
          <ToastContainer
            position="top-center"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            pauseOnHover
            draggable
            theme="dark" />
        
      </body>
    </html>
  );
}
