"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainContext from "@/contexts/MainContext";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/NavBar";
import Loader from "@/components/Loader";
import { useEffect, useState } from "react";
import Footer from "@/components/Footer";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
   const [loading, setLoading] = useState(true);

  // const router = useRouter();

  // Handles window load event
  useEffect(() => {
    const handleLoad = () => {
      setTimeout(() => setLoading(false), 2000);
    };

    if (document.readyState === 'complete') {
      handleLoad();
    } else {
      window.addEventListener("load", handleLoad);
    }

    return () => {
      window.removeEventListener("load", handleLoad);
    };
  }, []);


  return (
    <html lang="en" className=" overflow-x-hidden " >
      <body className=" 
        bg-blue-950 
      ">
          {loading && <Loader />}
          {!loading && <Navbar />}
          {!loading && children}
          {!loading && <Footer />}
          <ToastContainer
            position="top-center"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            pauseOnHover
            draggable
            theme="dark" />
        
      </body>
    </html>
  );
}
